version: "3.9"

services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    healthcheck:
      test: ["CMD", "consul", "info"]
      interval: 10s
      timeout: 5s
      retries: 3

  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "8060:8060"
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/local-config.yml
    command: -config.file=/etc/loki/local-config.yml

  alloy:
    image: grafana/alloy:v1.0.0
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./monitoring/alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - loki

  mysql_order:
    image: mysql:8.0
    container_name: mysql_order
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: order_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_invoice:
    image: mysql:8.0
    container_name: mysql_invoice
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: invoice_db
    ports:
      - "3310:3306"
    volumes:
      - mysql_invoice_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysql_order
      RABBITMQ_HOST: rabbitmq
      CONSUL_HOST: consul
    depends_on:
      mysql_order:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      consul:
        condition: service_healthy

  invoice-service:
    build: ./invoice-service
    container_name: invoice-service
    ports:
      - "8084:8084"
    environment:
      MYSQL_HOST: mysql_invoice
      RABBITMQ_HOST: rabbitmq
      CONSUL_HOST: consul
    depends_on:
      mysql_invoice:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      consul:
        condition: service_healthy

  oauth2:
    build: ./oauth2
    container_name: oauth2
    ports:
      - "8085:8085"
    environment:
      CONSUL_HOST: consul
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      consul:
        condition: service_healthy

  mysql_user:
    image: mysql:8.0
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: userdb
    ports:
      - "3308:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "7070:7070"
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql_user
    depends_on:
      mysql_user:
        condition: service_healthy
      consul:
        condition: service_healthy

  mysql_jwt:
    image: mysql:8.0
    container_name: mysql_jwt
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: jwt_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_jwt_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  jwt-auth-service:
    build: ./JWT-auth-service
    container_name: jwt-auth-service
    ports:
      - "8083:8083"
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql_jwt
    depends_on:
      mysql_jwt:
        condition: service_healthy
      consul:
        condition: service_healthy

  mysql_inventory:
    image: mysql:8.0
    container_name: mysql_inventory
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: inventorydb
    ports:
      - "3309:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8081:8081"
    environment:
      CONSUL_HOST: consul
      MYSQL_HOST: mysql_inventory
      RABBITMQ_HOST: rabbitmq
    depends_on:
      mysql_inventory:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      consul:
        condition: service_healthy

volumes:
  mysql_order_data:
  mysql_user_data:
  mysql_jwt_data:
  mysql_inventory_data:
  mysql_invoice_data:
