global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'gateway-service:8060'
          - 'order-service:8082'
          - 'inventory-service:8081'
          - 'oauth2:8085'
          - 'jwt-auth-service:8083'
          - 'user-service:7070'
 
