spring.application.name=invoice-service

spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root

#rabbitmq.exchange=order.invoice
rabbitmq.queue=invoice.queue
#rabbitmq.routing-key=invoice

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/invoice_db
#spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_db
spring.datasource.username=invoice_user
#spring.datasource.username=postgres
spring.datasource.password=123


# Consul
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health

# Prometheus
management.endpoints.web.exposure.include=health,metrics,prometheus