spring.application.name=invoice-service

spring.jpa.hibernate.ddl-auto=update

server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=root
spring.rabbitmq.password=root

#rabbitmq.exchange=order.invoice
rabbitmq.queue=invoice.queue
rabbitmq.routing-key=invoice

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_db
spring.datasource.username=invoice_user
spring.datasource.password=123