server:
  port: ${PORT:8060}

spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true
        health-check-path: /actuator/health
    gateway:
      routes:
        - id: auth-route
          uri: lb://oauth2
          predicates:
            - Path=/api/auth/**,/login/**,/oauth2/**,/
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: inventory-route
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: user-service 
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoices/**

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: "%5p [%X{traceId:-} %X{spanId:-}]"
